import { AIError, type AIProvider, type AIResult, type StreamChunk, type StructuredRequest, type TextRequest } from "./types";

type GroqResponse = { choices?: Array<{ message?: { content?: string }; finish_reason?: string }>; usage?: { prompt_tokens?: number; completion_tokens?: number; total_tokens?: number }; error?: { message?: string } };

export class GroqAIProvider implements AIProvider {
  readonly name = "groq";
  constructor(private readonly apiKey: string, private readonly defaultModel: string, private readonly defaultTimeoutMs: number) {}
  private body(request: TextRequest, stream = false) { return { model: request.model || this.defaultModel, messages: request.messages, temperature: request.temperature ?? 0.2, max_completion_tokens: request.maxTokens ?? 1200, stream, tools: request.tools?.map(tool => ({ type: "function", function: { name: tool.name, description: tool.description, parameters: tool.inputSchema } })) }; }
  private async call(body: Record<string, unknown>, timeoutMs?: number) { const response = await fetch("https://api.groq.com/openai/v1/chat/completions", { method: "POST", headers: { authorization: `Bearer ${this.apiKey}`, "content-type": "application/json" }, body: JSON.stringify(body), signal: AbortSignal.timeout(timeoutMs || this.defaultTimeoutMs) }).catch(error => { if (error instanceof Error && error.name === "TimeoutError") throw new AIError("AI request timed out.", "timeout", true); throw new AIError("AI provider is unavailable.", "provider", true); }); if (!response.ok) { const detail = await response.json().catch(() => null) as GroqResponse | null; throw new AIError(detail?.error?.message || `AI provider returned ${response.status}.`, response.status === 429 ? "rate_limit" : "provider", response.status >= 429); } return response; }
  async generateText(request: TextRequest): Promise<AIResult<string>> { const started = Date.now(); const response = await this.call(this.body(request), request.timeoutMs); const result = await response.json() as GroqResponse; const value = result.choices?.[0]?.message?.content; if (!value) throw new AIError("AI provider returned no text.", "invalid_output"); return { value, model: request.model || this.defaultModel, provider: this.name, usage: { inputTokens: result.usage?.prompt_tokens, outputTokens: result.usage?.completion_tokens, totalTokens: result.usage?.total_tokens }, latencyMs: Date.now() - started, finishReason: result.choices?.[0]?.finish_reason }; }
  async generateStructured<T>(request: StructuredRequest<T>): Promise<AIResult<T>> { const started = Date.now(); const response = await this.call({ ...this.body(request), response_format: { type: "json_schema", json_schema: { name: request.schemaName, strict: true, schema: request.jsonSchema } } }, request.timeoutMs); const result = await response.json() as GroqResponse; const raw = result.choices?.[0]?.message?.content; if (!raw) throw new AIError("AI provider returned no structured output.", "invalid_output"); let value: unknown; try { value = JSON.parse(raw); } catch { throw new AIError("AI provider returned invalid JSON.", "invalid_output"); } const parsed = request.schema.safeParse(value); if (!parsed.success) throw new AIError("AI provider output did not match the requested schema.", "invalid_output"); return { value: parsed.data, model: request.model || this.defaultModel, provider: this.name, usage: { inputTokens: result.usage?.prompt_tokens, outputTokens: result.usage?.completion_tokens, totalTokens: result.usage?.total_tokens }, latencyMs: Date.now() - started, finishReason: result.choices?.[0]?.finish_reason }; }
  async *streamText(request: TextRequest): AsyncIterable<StreamChunk> { const response = await this.call(this.body(request, true), request.timeoutMs); if (!response.body) throw new AIError("AI stream is unavailable.", "provider", true); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split("\n"); buffer = lines.pop() || ""; for (const line of lines) { if (!line.startsWith("data: ")) continue; const data = line.slice(6); if (data === "[DONE]") { yield { delta: "", done: true }; return; } try { const chunk = JSON.parse(data) as { choices?: Array<{ delta?: { content?: string } }> }; const delta = chunk.choices?.[0]?.delta?.content; if (delta) yield { delta }; } catch { /* ignore partial provider events */ } } } yield { delta: "", done: true }; }
}
