"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";

async function send(body: Record<string, unknown>) { const response = await fetch("/api/admin/mentorship-operations", { method: "POST", credentials: "include", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "Unable to update mentorship workflow."); }

export function MentorDecision({ mentorId }: { mentorId: string | number }) { const router = useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); async function decide(decision:"approved"|"rejected") { const reason = decision === "rejected" ? window.prompt("Explain the rejection to the applicant (minimum 10 characters):") : "Staff approved mentor application."; if (reason === null || !window.confirm(`${decision === "approved" ? "Approve" : "Reject"} this mentor application?`)) return; setBusy(true); setError(""); try { await send({ action:"mentor-decision", mentorId, decision, reason }); router.refresh(); } catch(caught) { setError(caught instanceof Error ? caught.message : "Unable to update."); } finally { setBusy(false); } } return <div className="smn-ops-actions"><button disabled={busy} onClick={()=>decide("approved")} type="button">Approve</button><button disabled={busy} onClick={()=>decide("rejected")} type="button">Reject</button>{error?<span role="alert">{error}</span>:null}</div>; }

export function RequestTransition({ requestId, current }: { requestId: string | number; current: string }) { const router=useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); async function transition(status:string) { const requiresReason=status==="declined"; const reason=requiresReason?window.prompt("Explain why this request is declined (minimum 10 characters):"): `Staff moved request from ${current} to ${status}.`; if(reason===null||!window.confirm(`Move this request to ${status}?`))return; setBusy(true);setError("");try{await send({action:"request-transition",requestId,status,reason});router.refresh();}catch(caught){setError(caught instanceof Error?caught.message:"Unable to update.");}finally{setBusy(false);} } return <div className="smn-ops-actions"><button disabled={busy||current==="reviewing"} onClick={()=>transition("reviewing")} type="button">Review</button><button disabled={busy||current==="introduced"} onClick={()=>transition("introduced")} type="button">Introduce</button><button disabled={busy||current==="completed"} onClick={()=>transition("completed")} type="button">Complete</button><button disabled={busy||current==="declined"} onClick={()=>transition("declined")} type="button">Decline</button>{error?<span role="alert">{error}</span>:null}</div>; }
