"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, Briefcase, MapPin, Search } from "lucide-react";
import type { OpportunityItem } from "@/lib/opportunities";

const field = "field w-full rounded-2xl border border-white/10 bg-white/5 px-4 py-3 text-white placeholder:text-white/35";
const label: Record<string, string> = { manual: "SMN verified", partner: "Partner listing", imported: "External opportunity" };

export function OpportunityDirectory({ opportunities }: { opportunities: OpportunityItem[] }) {
  const [query, setQuery] = useState(""); const [type, setType] = useState("All types"); const [mode, setMode] = useState("All modes");
  const types = useMemo(() => ["All types", ...Array.from(new Set(opportunities.map((item) => item.type))).sort()], [opportunities]);
  const modes = useMemo(() => ["All modes", ...Array.from(new Set(opportunities.map((item) => item.workMode))).sort()], [opportunities]);
  const filtered = opportunities.filter((item) => `${item.title} ${item.company} ${item.summary} ${item.location}`.toLowerCase().includes(query.toLowerCase()) && (type === "All types" || item.type === type) && (mode === "All modes" || item.workMode === mode));
  return <div className="space-y-5"><div className="grid gap-3 md:grid-cols-[1fr_180px_180px]"><label className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-white/35" /><input aria-label="Search opportunities" className={`${field} pl-11`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search roles, companies, or locations" /></label><select aria-label="Filter by type" className={`${field} bg-surface`} value={type} onChange={(event) => setType(event.target.value)}>{types.map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Filter by work mode" className={`${field} bg-surface`} value={mode} onChange={(event) => setMode(event.target.value)}>{modes.map((item) => <option key={item}>{item}</option>)}</select></div>
  {filtered.length ? <div className="grid gap-4 lg:grid-cols-2">{filtered.map((item) => <Link key={item.id} href={`/app/opportunities/${item.slug}`} className="group rounded-2xl border border-white/10 bg-surface p-5 transition hover:border-baby-blue/35 sm:p-6"><div className="flex items-start justify-between gap-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/5 text-baby-blue"><Briefcase className="h-5 w-5" /></div><span className="rounded-full border border-white/10 px-2.5 py-1 text-[10px] uppercase tracking-wide text-white/40">{label[item.sourceLabel] || "Opportunity"}</span></div><h2 className="mt-5 font-display text-xl text-white group-hover:text-baby-blue">{item.title}</h2><p className="mt-1 text-sm text-baby-blue">{item.company}</p><p className="mt-3 line-clamp-3 text-sm leading-relaxed text-white/50">{item.summary}</p><div className="mt-5 flex flex-wrap gap-2 text-xs text-white/45"><span>{item.type}</span><span>·</span><span>{item.workMode}</span><span>·</span><span className="flex items-center gap-1"><MapPin className="h-3 w-3" />{item.location}</span></div><span className="mt-5 inline-flex items-center gap-1 text-sm text-baby-blue">View opportunity <ArrowRight className="h-3.5 w-3.5" /></span></Link>)}</div> : <div className="rounded-2xl border border-dashed border-white/15 p-8 text-center text-sm text-white/50">No opportunities match those filters.</div>}</div>;
}