/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    members: Member;
    mentors: Mentor;
    'mentorship-requests': MentorshipRequest;
    'mentorship-relationships': MentorshipRelationship;
    'opportunity-sources': OpportunitySource;
    opportunities: Opportunity;
    'opportunity-applications': OpportunityApplication;
    'cohort-applications': CohortApplication;
    enrollments: Enrollment;
    'lms-courses': LmsCourse;
    'lms-modules': LmsModule;
    'lms-lessons': LmsLesson;
    'lms-lesson-progress': LmsLessonProgress;
    'lms-assessments': LmsAssessment;
    'lms-submissions': LmsSubmission;
    portfolios: Portfolio;
    certificates: Certificate;
    'audit-events': AuditEvent;
    'member-notes': MemberNote;
    'event-registrations': EventRegistration;
    payments: Payment;
    'ai-usage-records': AiUsageRecord;
    'ai-feedback': AiFeedback;
    'ai-knowledge-sources': AiKnowledgeSource;
    'ai-drafts': AiDraft;
    'ai-career-states': AiCareerState;
    media: Media;
    posts: Post;
    courses: Course;
    events: Event;
    stories: Story;
    resources: Resource;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    mentors: MentorsSelect<false> | MentorsSelect<true>;
    'mentorship-requests': MentorshipRequestsSelect<false> | MentorshipRequestsSelect<true>;
    'mentorship-relationships': MentorshipRelationshipsSelect<false> | MentorshipRelationshipsSelect<true>;
    'opportunity-sources': OpportunitySourcesSelect<false> | OpportunitySourcesSelect<true>;
    opportunities: OpportunitiesSelect<false> | OpportunitiesSelect<true>;
    'opportunity-applications': OpportunityApplicationsSelect<false> | OpportunityApplicationsSelect<true>;
    'cohort-applications': CohortApplicationsSelect<false> | CohortApplicationsSelect<true>;
    enrollments: EnrollmentsSelect<false> | EnrollmentsSelect<true>;
    'lms-courses': LmsCoursesSelect<false> | LmsCoursesSelect<true>;
    'lms-modules': LmsModulesSelect<false> | LmsModulesSelect<true>;
    'lms-lessons': LmsLessonsSelect<false> | LmsLessonsSelect<true>;
    'lms-lesson-progress': LmsLessonProgressSelect<false> | LmsLessonProgressSelect<true>;
    'lms-assessments': LmsAssessmentsSelect<false> | LmsAssessmentsSelect<true>;
    'lms-submissions': LmsSubmissionsSelect<false> | LmsSubmissionsSelect<true>;
    portfolios: PortfoliosSelect<false> | PortfoliosSelect<true>;
    certificates: CertificatesSelect<false> | CertificatesSelect<true>;
    'audit-events': AuditEventsSelect<false> | AuditEventsSelect<true>;
    'member-notes': MemberNotesSelect<false> | MemberNotesSelect<true>;
    'event-registrations': EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'ai-usage-records': AiUsageRecordsSelect<false> | AiUsageRecordsSelect<true>;
    'ai-feedback': AiFeedbackSelect<false> | AiFeedbackSelect<true>;
    'ai-knowledge-sources': AiKnowledgeSourcesSelect<false> | AiKnowledgeSourcesSelect<true>;
    'ai-drafts': AiDraftsSelect<false> | AiDraftsSelect<true>;
    'ai-career-states': AiCareerStatesSelect<false> | AiCareerStatesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    stories: StoriesSelect<false> | StoriesSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Staff accounts for the SMN staff app at /staff.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Least-privilege responsibility for this staff account.
   */
  role: 'super-admin' | 'content' | 'learning' | 'mentorship' | 'opportunity' | 'support' | 'analyst';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Member accounts for the SMN portal (not CMS staff).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  /**
   * Public profile slug, e.g. ada-okonkwo
   */
  handle?: string | null;
  headline?: string | null;
  bio?: string | null;
  skills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Member-authored goals; only used by Career Coach when enabled.
   */
  careerGoals?: string | null;
  careerInterests?:
    | {
        interest: string;
        id?: string | null;
      }[]
    | null;
  location?: string | null;
  linkedin?: string | null;
  portfolioUrl?: string | null;
  avatar?: (number | null) | Media;
  roles?: ('member' | 'mentor' | 'employer' | 'alumni')[] | null;
  /**
   * Set by staff after applications / cohort intake.
   */
  cohortStatus?: ('none' | 'applicant' | 'active' | 'completed') | null;
  visibility?: ('private' | 'members' | 'public') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Mentor profiles. Only approved profiles appear in the member directory.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentors".
 */
export interface Mentor {
  id: number;
  member: number | Member;
  title: string;
  bio: string;
  topics: (
    | 'Brand strategy'
    | 'Content strategy'
    | 'Social media'
    | 'AI workflows'
    | 'B2B marketing'
    | 'Growth marketing'
    | 'Portfolio reviews'
    | 'Career development'
  )[];
  seniority: 'Mid-level' | 'Senior' | 'Lead / Head' | 'Founder / Executive';
  availability: 'Available' | 'Limited' | 'Unavailable';
  /**
   * Introductions are blocked when this capacity is reached.
   */
  maxActiveMentees: number;
  bookingUrl?: string | null;
  status: 'draft' | 'approved' | 'paused' | 'rejected';
  featured?: boolean | null;
  approvedAt?: string | null;
  approvedBy?: (number | null) | User;
  rejectionReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentorship-requests".
 */
export interface MentorshipRequest {
  id: number;
  requester: number | Member;
  mentor: number | Mentor;
  topic:
    | 'Brand strategy'
    | 'Content strategy'
    | 'Social media'
    | 'AI workflows'
    | 'B2B marketing'
    | 'Growth marketing'
    | 'Portfolio reviews'
    | 'Career development';
  goal: string;
  message: string;
  preferredFormat: 'Video call' | 'Portfolio review' | 'Async feedback' | 'Group office hours';
  status: 'new' | 'reviewing' | 'introduced' | 'completed' | 'declined';
  staffNotes?: string | null;
  decisionReason?: string | null;
  mentorResponse?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentorship-relationships".
 */
export interface MentorshipRelationship {
  id: number;
  request: number | MentorshipRequest;
  mentor: number | Mentor;
  mentee: number | Member;
  status: 'proposed' | 'active' | 'completed' | 'cancelled';
  startedAt?: string | null;
  endedAt?: string | null;
  mentorResponse?: string | null;
  menteeFeedback?: string | null;
  mentorFeedback?: string | null;
  staffNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunity-sources".
 */
export interface OpportunitySource {
  id: number;
  name: string;
  type: 'greenhouse' | 'lever' | 'ashby';
  /**
   * The public board/site identifier from the ATS careers URL.
   */
  boardToken: string;
  enabled?: boolean | null;
  /**
   * Only enable after the source has proven consistently relevant.
   */
  autoPublish?: boolean | null;
  minimumScore?: number | null;
  defaultLocation?: string | null;
  lastSyncedAt?: string | null;
  lastError?: string | null;
  consecutiveFailures?: number | null;
  lastFetchedCount?: number | null;
  lastCreatedCount?: number | null;
  lastUpdatedCount?: number | null;
  lastSkippedCount?: number | null;
  lastDurationMs?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities".
 */
export interface Opportunity {
  id: number;
  title: string;
  slug: string;
  company: string;
  summary: string;
  description?: string | null;
  type: 'Full-time' | 'Part-time' | 'Contract' | 'Freelance' | 'Internship' | 'Volunteer';
  workMode: 'Remote' | 'Hybrid' | 'On-site' | 'Unspecified';
  experienceLevel: 'Entry level' | 'Mid-level' | 'Senior' | 'Lead / Head' | 'Any level';
  location: string;
  salary?: string | null;
  applicationUrl: string;
  source?: (number | null) | OpportunitySource;
  externalId?: string | null;
  fingerprint?: string | null;
  sourceLabel: 'manual' | 'partner' | 'imported';
  relevanceScore?: number | null;
  status: 'pending' | 'published' | 'closed' | 'archived';
  publishedAt?: string | null;
  expiresAt?: string | null;
  lastSeenAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunity-applications".
 */
export interface OpportunityApplication {
  id: number;
  member: number | Member;
  opportunity: number | Opportunity;
  status: 'started' | 'applied' | 'interviewing' | 'offered' | 'declined' | 'withdrawn';
  appliedAt?: string | null;
  memberNotes?: string | null;
  staffNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Public flagship cohort applications from /apply.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cohort-applications".
 */
export interface CohortApplication {
  id: number;
  name: string;
  email: string;
  phone: string;
  country: string;
  role: string;
  level: string;
  linkedin?: string | null;
  portfolio?: string | null;
  goals: string;
  source?: string | null;
  /**
   * Published cohort this application is for.
   */
  course?: (number | null) | LmsCourse;
  status: 'received' | 'reviewing' | 'accepted' | 'waitlisted' | 'declined';
  member?: (number | null) | Member;
  staffNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lms-courses".
 */
export interface LmsCourse {
  id: number;
  title: string;
  slug: string;
  summary: string;
  /**
   * Instructor or facilitator shown for this course.
   */
  instructor?: string | null;
  category?: string | null;
  /**
   * Use ‘None’ when the course has no prerequisites.
   */
  prerequisites?: string | null;
  learningOutcomes?:
    | {
        outcome: string;
        id?: string | null;
      }[]
    | null;
  programKey: string;
  /**
   * Self-paced lessons live in SMN. Cohort sessions use the Google Classroom invite. Assessments stay in SMN for both.
   */
  delivery: 'self-paced' | 'cohort';
  /**
   * Purchase courses checkout on the public catalogue. Apply-first courses use /apply, then staff grant access or send a payment link.
   */
  commerce: 'purchase' | 'apply';
  /**
   * Checkout amount in pesewas. Required for Buy now once the fee is confirmed.
   */
  amount?: number | null;
  currency?: string | null;
  /**
   * Optional public price label. Blank uses the confirmed GH₵ format from amount.
   */
  price?: string | null;
  badge?: string | null;
  /**
   * Use this published cohort as the next intake on the homepage and apply page.
   */
  featured?: boolean | null;
  startDate?: string | null;
  applicationDeadline?: string | null;
  duration?: string | null;
  seats?: number | null;
  audience?: string | null;
  format?: string | null;
  sessions?: string | null;
  /**
   * Only enable after the fee is confirmed. When off, the site shows Contact SMN for current fees.
   */
  priceConfirmed?: boolean | null;
  /**
   * Public fee once confirmed, e.g. GH₵2,500.
   */
  priceLabel?: string | null;
  priceNote?: string | null;
  accessRule: 'enrolled' | 'member' | 'cohort';
  level?: ('foundation' | 'intermediate' | 'advanced') | null;
  cover?: (number | null) | Media;
  estimatedHours?: number | null;
  /**
   * Google Classroom invite for this cohort. Copied onto enrollments and Classroom lessons.
   */
  classroomUrl?: string | null;
  enrollmentOpen?: boolean | null;
  certificateEnabled?: boolean | null;
  previewEnabled?: boolean | null;
  /**
   * Requires the environment Tutor feature flag and approved course material.
   */
  tutorEnabled?: boolean | null;
  tutorModes?:
    | (
        | 'explain'
        | 'simplify'
        | 'example'
        | 'summary'
        | 'revision'
        | 'socratic'
        | 'feedback'
        | 'compare'
        | 'next-lesson'
      )[]
    | null;
  /**
   * Optional instructor guidance. This never overrides safety or grounding policy.
   */
  tutorGuidance?: string | null;
  order?: number | null;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments".
 */
export interface Enrollment {
  id: number;
  member: number | Member;
  programName: string;
  /**
   * Stable key shared with the LMS course, e.g. cohort-2026 or ai-marketers.
   */
  programKey: string;
  course?: (number | null) | LmsCourse;
  programType: 'Cohort' | 'Self-paced course' | 'Workshop' | 'Community track';
  source: 'staff' | 'cohort' | 'paystack' | 'selar';
  /**
   * Paystack reference or legacy order id.
   */
  externalReference?: string | null;
  status: 'active' | 'completed' | 'paused' | 'cancelled';
  /**
   * Google Classroom / live class link.
   */
  classroomUrl?: string | null;
  /**
   * Optional external learning URL.
   */
  courseUrl?: string | null;
  startsAt?: string | null;
  endsAt?: string | null;
  startedAt?: string | null;
  lastActivityAt?: string | null;
  completedAt?: string | null;
  completionPercent?: number | null;
  certificateEligible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lms-modules".
 */
export interface LmsModule {
  id: number;
  course: number | LmsCourse;
  title: string;
  slug: string;
  summary?: string | null;
  order?: number | null;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lms-lessons".
 */
export interface LmsLesson {
  id: number;
  course: number | LmsCourse;
  module: number | LmsModule;
  title: string;
  slug: string;
  summary: string;
  lessonType: 'video' | 'reading' | 'download' | 'assignment' | 'classroom';
  /**
   * Optional Classroom link for this session. Blank uses the cohort invite on the course.
   */
  classroomUrl?: string | null;
  /**
   * When this live session starts.
   */
  sessionAt?: string | null;
  /**
   * Optional unlisted YouTube watch/share/embed URL. Videos are streamed by YouTube, not stored in R2.
   */
  youtubeUrl?: string | null;
  durationMinutes?: number | null;
  /**
   * Lesson text, reading content, article notes, prompts, or assignment instructions.
   */
  body?: string | null;
  /**
   * Optional label for an external article or resource link.
   */
  resourceLabel?: string | null;
  /**
   * Optional external article, Notion page, Google Doc, or other resource URL.
   */
  resourceUrl?: string | null;
  /**
   * Downloadable documents and files for learners.
   */
  attachments?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lms-lesson-progress".
 */
export interface LmsLessonProgress {
  id: number;
  member: number | Member;
  course: number | LmsCourse;
  lesson: number | LmsLesson;
  status: 'not-started' | 'in-progress' | 'completed';
  completedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lms-assessments".
 */
export interface LmsAssessment {
  id: number;
  course: number | LmsCourse;
  module?: (number | null) | LmsModule;
  lesson?: (number | null) | LmsLesson;
  title: string;
  slug: string;
  kind: 'assignment' | 'quiz';
  instructions: string;
  availableFrom?: string | null;
  dueAt?: string | null;
  allowLate?: boolean | null;
  maxAttempts?: number | null;
  totalMarks?: number | null;
  questions?:
    | {
        prompt: string;
        type: 'multiple-choice' | 'short-answer';
        options?:
          | {
              option: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Hidden from learners. Used to auto-score multiple choice.
         */
        answer?: string | null;
        marks: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Used when staff score assignments and short answers.
   */
  rubric?:
    | {
        criterion: string;
        description?: string | null;
        levels?:
          | {
              label: string;
              descriptor?: string | null;
              marks: number;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lms-submissions".
 */
export interface LmsSubmission {
  id: number;
  assessment: number | LmsAssessment;
  course: number | LmsCourse;
  member: number | Member;
  attemptNumber: number;
  status: 'in-progress' | 'submitted' | 'graded' | 'returned';
  answers?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  textResponse?: string | null;
  files?:
    | {
        label: string;
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  late?: boolean | null;
  submittedAt?: string | null;
  score?: number | null;
  maxScore?: number | null;
  feedback?: string | null;
  rubricScores?:
    | {
        criterion: string;
        marks: number;
        comment?: string | null;
        id?: string | null;
      }[]
    | null;
  gradedBy?: (number | null) | User;
  gradedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios".
 */
export interface Portfolio {
  id: number;
  member: number | Member;
  title: string;
  slug: string;
  summary: string;
  challenge: string;
  approach: string;
  outcome: string;
  skills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  projectUrl?: string | null;
  cover?: (number | null) | Media;
  /**
   * Optional external image URL. Used when no cover upload is set.
   */
  coverUrl?: string | null;
  status: 'draft' | 'published';
  visibility: 'private' | 'members' | 'public';
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates".
 */
export interface Certificate {
  id: number;
  member: number | Member;
  title: string;
  programName: string;
  programKey?: string | null;
  course?: (number | null) | LmsCourse;
  enrollment?: (number | null) | Enrollment;
  issuedBy: number | User;
  activeIssuanceKey?: string | null;
  credentialCode: string;
  summary?: string | null;
  skills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload the issued PDF certificate.
   */
  pdf?: (number | null) | Media;
  issuedAt: string;
  expiresAt?: string | null;
  reissuedFrom?: (number | null) | Certificate;
  revokedAt?: string | null;
  revokedBy?: (number | null) | User;
  revocationReason?: string | null;
  notificationStatus?: ('pending' | 'sent' | 'skipped' | 'failed') | null;
  status: 'draft' | 'valid' | 'revoked';
  visibility: 'private' | 'public';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events".
 */
export interface AuditEvent {
  id: number;
  actor: number | User;
  action: string;
  entityType: string;
  entityId: string;
  reason: string;
  before?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  after?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  visibility: 'staff' | 'member-visible';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-notes".
 */
export interface MemberNote {
  id: number;
  member: number | Member;
  author: number | User;
  category: 'support' | 'learning' | 'mentorship' | 'opportunity' | 'conduct' | 'other';
  note: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  member: number | Member;
  status: 'pending_payment' | 'confirmed' | 'cancelled' | 'checked_in' | 'no_show';
  ticketCode?: string | null;
  paystackReference?: string | null;
  amountPaid?: number | null;
  currency?: string | null;
  registeredAt?: string | null;
  checkedInAt?: string | null;
  checkedInBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  status: 'draft' | 'published' | 'cancelled';
  type: 'Webinar' | 'Workshop' | 'Networking' | 'Conference';
  format: 'online' | 'onsite' | 'hybrid';
  pricing: 'free' | 'paid';
  /**
   * Price in minor units (pesewas). Required when paid.
   */
  amount?: number | null;
  currency?: string | null;
  capacity?: number | null;
  venue?: string | null;
  address?: string | null;
  /**
   * Meet / Classroom / Zoom link shown after registration.
   */
  onlineUrl?: string | null;
  startsAt: string;
  endsAt?: string | null;
  /**
   * Legacy display date; prefer startsAt.
   */
  date?: string | null;
  /**
   * Legacy time label.
   */
  time?: string | null;
  host?: string | null;
  summary: string;
  body?: string | null;
  /**
   * Legacy external URL — leave blank for first-party registration.
   */
  registrationUrl?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: number;
  kind: 'event' | 'course';
  member: number | Member;
  /**
   * Amount in minor units (e.g. pesewas).
   */
  amount: number;
  currency: string;
  status: 'initialized' | 'success' | 'failed' | 'needs_refund' | 'refunded';
  paystackReference: string;
  paystackAccessCode?: string | null;
  event?: (number | null) | Event;
  course?: (number | null) | LmsCourse;
  catalogueCourse?: (number | null) | Course;
  application?: (number | null) | CohortApplication;
  enrollment?: (number | null) | Enrollment;
  eventRegistration?: (number | null) | EventRegistration;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  slug: string;
  summary: string;
  outcomes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  duration?: string | null;
  lessons?: number | null;
  /**
   * Display label (optional if amount is set).
   */
  price?: string | null;
  /**
   * Checkout amount in minor units (pesewas). 0 = free catalog item.
   */
  amount?: number | null;
  currency?: string | null;
  /**
   * Must match the LMS course program key to unlock access after Paystack.
   */
  programKey?: string | null;
  delivery?: ('self-paced' | 'live') | null;
  /**
   * Default Google Classroom link for live programmes.
   */
  classroomUrl?: string | null;
  /**
   * Optional link to the native LMS course.
   */
  lmsCourse?: (number | null) | LmsCourse;
  /**
   * Legacy Selar URL — unused for new checkouts.
   */
  selarUrl?: string | null;
  badge?: string | null;
  image?: (number | null) | Media;
  status?: ('published' | 'coming-soon') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usage-records".
 */
export interface AiUsageRecord {
  id: number;
  actorType: 'member' | 'staff' | 'system';
  /**
   * Opaque actor identifier; never email or display name.
   */
  actorKey: string;
  feature: 'tutor' | 'content-studio' | 'career-coach' | 'retrieval' | 'tool';
  operation: string;
  provider?: string | null;
  model?: string | null;
  status: 'success' | 'declined' | 'error' | 'timeout' | 'limited';
  inputChars?: number | null;
  outputChars?: number | null;
  inputTokens?: number | null;
  outputTokens?: number | null;
  latencyMs?: number | null;
  sourceCount?: number | null;
  promptHash?: string | null;
  errorCode?: string | null;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-feedback".
 */
export interface AiFeedback {
  id: number;
  member: number | Member;
  feature: 'tutor' | 'content-studio' | 'career-coach';
  contextKey?: string | null;
  rating: 'helpful' | 'not-helpful';
  reason?: ('incorrect' | 'unsupported' | 'unclear' | 'unsafe' | 'irrelevant' | 'other') | null;
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-knowledge-sources".
 */
export interface AiKnowledgeSource {
  id: number;
  course: number | LmsCourse;
  lesson?: (number | null) | LmsLesson;
  kind: 'transcript' | 'note' | 'resource' | 'faq' | 'attachment-text';
  title: string;
  content: string;
  citationLabel: string;
  approved?: boolean | null;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-drafts".
 */
export interface AiDraft {
  id: number;
  course: number | LmsCourse;
  lesson?: (number | null) | LmsLesson;
  kind: 'course-outline' | 'lesson-outline' | 'lesson' | 'example' | 'quiz' | 'rubric' | 'revision' | 'faq';
  title: string;
  content:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'draft' | 'selected' | 'rejected' | 'saved';
  version: number;
  parentDraft?: (number | null) | AiDraft;
  createdBy: number | User;
  provenance:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  controls?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-career-states".
 */
export interface AiCareerState {
  id: number;
  member: number | Member;
  goalSummary?: string | null;
  confirmedPlan?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  savedOpportunityIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  savedCourseIds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  conversationSummary?: string | null;
  retentionConsentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  category:
    | 'Marketing Strategy'
    | 'AI'
    | 'Social Media'
    | 'Career Development'
    | 'Case Studies'
    | 'Industry Trends'
    | 'Community Stories';
  excerpt: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cover?: (number | null) | Media;
  publishedAt?: string | null;
  readTime?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Member testimonials. Only stories with Published enabled appear on the public site. Do not publish fictional or seed content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories".
 */
export interface Story {
  id: number;
  name: string;
  role: string;
  /**
   * Programme or cohort name (optional)
   */
  programme?: string | null;
  quote: string;
  image?: (number | null) | Media;
  /**
   * Optional public portfolio or case-study link
   */
  portfolioUrl?: string | null;
  /**
   * Confirm the member gave permission to publish this testimonial
   */
  permissionConfirmed?: boolean | null;
  /**
   * Public site only shows published testimonials with permission confirmed
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  slug: string;
  type: 'Template' | 'Guide' | 'AI Prompts' | 'Checklist' | 'Toolkit' | 'Download';
  description: string;
  file?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'mentors';
        value: number | Mentor;
      } | null)
    | ({
        relationTo: 'mentorship-requests';
        value: number | MentorshipRequest;
      } | null)
    | ({
        relationTo: 'mentorship-relationships';
        value: number | MentorshipRelationship;
      } | null)
    | ({
        relationTo: 'opportunity-sources';
        value: number | OpportunitySource;
      } | null)
    | ({
        relationTo: 'opportunities';
        value: number | Opportunity;
      } | null)
    | ({
        relationTo: 'opportunity-applications';
        value: number | OpportunityApplication;
      } | null)
    | ({
        relationTo: 'cohort-applications';
        value: number | CohortApplication;
      } | null)
    | ({
        relationTo: 'enrollments';
        value: number | Enrollment;
      } | null)
    | ({
        relationTo: 'lms-courses';
        value: number | LmsCourse;
      } | null)
    | ({
        relationTo: 'lms-modules';
        value: number | LmsModule;
      } | null)
    | ({
        relationTo: 'lms-lessons';
        value: number | LmsLesson;
      } | null)
    | ({
        relationTo: 'lms-lesson-progress';
        value: number | LmsLessonProgress;
      } | null)
    | ({
        relationTo: 'lms-assessments';
        value: number | LmsAssessment;
      } | null)
    | ({
        relationTo: 'lms-submissions';
        value: number | LmsSubmission;
      } | null)
    | ({
        relationTo: 'portfolios';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'certificates';
        value: number | Certificate;
      } | null)
    | ({
        relationTo: 'audit-events';
        value: number | AuditEvent;
      } | null)
    | ({
        relationTo: 'member-notes';
        value: number | MemberNote;
      } | null)
    | ({
        relationTo: 'event-registrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'payments';
        value: number | Payment;
      } | null)
    | ({
        relationTo: 'ai-usage-records';
        value: number | AiUsageRecord;
      } | null)
    | ({
        relationTo: 'ai-feedback';
        value: number | AiFeedback;
      } | null)
    | ({
        relationTo: 'ai-knowledge-sources';
        value: number | AiKnowledgeSource;
      } | null)
    | ({
        relationTo: 'ai-drafts';
        value: number | AiDraft;
      } | null)
    | ({
        relationTo: 'ai-career-states';
        value: number | AiCareerState;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'stories';
        value: number | Story;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  handle?: T;
  headline?: T;
  bio?: T;
  skills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  careerGoals?: T;
  careerInterests?:
    | T
    | {
        interest?: T;
        id?: T;
      };
  location?: T;
  linkedin?: T;
  portfolioUrl?: T;
  avatar?: T;
  roles?: T;
  cohortStatus?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentors_select".
 */
export interface MentorsSelect<T extends boolean = true> {
  member?: T;
  title?: T;
  bio?: T;
  topics?: T;
  seniority?: T;
  availability?: T;
  maxActiveMentees?: T;
  bookingUrl?: T;
  status?: T;
  featured?: T;
  approvedAt?: T;
  approvedBy?: T;
  rejectionReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentorship-requests_select".
 */
export interface MentorshipRequestsSelect<T extends boolean = true> {
  requester?: T;
  mentor?: T;
  topic?: T;
  goal?: T;
  message?: T;
  preferredFormat?: T;
  status?: T;
  staffNotes?: T;
  decisionReason?: T;
  mentorResponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mentorship-relationships_select".
 */
export interface MentorshipRelationshipsSelect<T extends boolean = true> {
  request?: T;
  mentor?: T;
  mentee?: T;
  status?: T;
  startedAt?: T;
  endedAt?: T;
  mentorResponse?: T;
  menteeFeedback?: T;
  mentorFeedback?: T;
  staffNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunity-sources_select".
 */
export interface OpportunitySourcesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  boardToken?: T;
  enabled?: T;
  autoPublish?: T;
  minimumScore?: T;
  defaultLocation?: T;
  lastSyncedAt?: T;
  lastError?: T;
  consecutiveFailures?: T;
  lastFetchedCount?: T;
  lastCreatedCount?: T;
  lastUpdatedCount?: T;
  lastSkippedCount?: T;
  lastDurationMs?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunities_select".
 */
export interface OpportunitiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  company?: T;
  summary?: T;
  description?: T;
  type?: T;
  workMode?: T;
  experienceLevel?: T;
  location?: T;
  salary?: T;
  applicationUrl?: T;
  source?: T;
  externalId?: T;
  fingerprint?: T;
  sourceLabel?: T;
  relevanceScore?: T;
  status?: T;
  publishedAt?: T;
  expiresAt?: T;
  lastSeenAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "opportunity-applications_select".
 */
export interface OpportunityApplicationsSelect<T extends boolean = true> {
  member?: T;
  opportunity?: T;
  status?: T;
  appliedAt?: T;
  memberNotes?: T;
  staffNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cohort-applications_select".
 */
export interface CohortApplicationsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  country?: T;
  role?: T;
  level?: T;
  linkedin?: T;
  portfolio?: T;
  goals?: T;
  source?: T;
  course?: T;
  status?: T;
  member?: T;
  staffNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enrollments_select".
 */
export interface EnrollmentsSelect<T extends boolean = true> {
  member?: T;
  programName?: T;
  programKey?: T;
  course?: T;
  programType?: T;
  source?: T;
  externalReference?: T;
  status?: T;
  classroomUrl?: T;
  courseUrl?: T;
  startsAt?: T;
  endsAt?: T;
  startedAt?: T;
  lastActivityAt?: T;
  completedAt?: T;
  completionPercent?: T;
  certificateEligible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lms-courses_select".
 */
export interface LmsCoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  instructor?: T;
  category?: T;
  prerequisites?: T;
  learningOutcomes?:
    | T
    | {
        outcome?: T;
        id?: T;
      };
  programKey?: T;
  delivery?: T;
  commerce?: T;
  amount?: T;
  currency?: T;
  price?: T;
  badge?: T;
  featured?: T;
  startDate?: T;
  applicationDeadline?: T;
  duration?: T;
  seats?: T;
  audience?: T;
  format?: T;
  sessions?: T;
  priceConfirmed?: T;
  priceLabel?: T;
  priceNote?: T;
  accessRule?: T;
  level?: T;
  cover?: T;
  estimatedHours?: T;
  classroomUrl?: T;
  enrollmentOpen?: T;
  certificateEnabled?: T;
  previewEnabled?: T;
  tutorEnabled?: T;
  tutorModes?: T;
  tutorGuidance?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lms-modules_select".
 */
export interface LmsModulesSelect<T extends boolean = true> {
  course?: T;
  title?: T;
  slug?: T;
  summary?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lms-lessons_select".
 */
export interface LmsLessonsSelect<T extends boolean = true> {
  course?: T;
  module?: T;
  title?: T;
  slug?: T;
  summary?: T;
  lessonType?: T;
  classroomUrl?: T;
  sessionAt?: T;
  youtubeUrl?: T;
  durationMinutes?: T;
  body?: T;
  resourceLabel?: T;
  resourceUrl?: T;
  attachments?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lms-lesson-progress_select".
 */
export interface LmsLessonProgressSelect<T extends boolean = true> {
  member?: T;
  course?: T;
  lesson?: T;
  status?: T;
  completedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lms-assessments_select".
 */
export interface LmsAssessmentsSelect<T extends boolean = true> {
  course?: T;
  module?: T;
  lesson?: T;
  title?: T;
  slug?: T;
  kind?: T;
  instructions?: T;
  availableFrom?: T;
  dueAt?: T;
  allowLate?: T;
  maxAttempts?: T;
  totalMarks?: T;
  questions?:
    | T
    | {
        prompt?: T;
        type?: T;
        options?:
          | T
          | {
              option?: T;
              id?: T;
            };
        answer?: T;
        marks?: T;
        id?: T;
      };
  rubric?:
    | T
    | {
        criterion?: T;
        description?: T;
        levels?:
          | T
          | {
              label?: T;
              descriptor?: T;
              marks?: T;
              id?: T;
            };
        id?: T;
      };
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lms-submissions_select".
 */
export interface LmsSubmissionsSelect<T extends boolean = true> {
  assessment?: T;
  course?: T;
  member?: T;
  attemptNumber?: T;
  status?: T;
  answers?: T;
  textResponse?: T;
  files?:
    | T
    | {
        label?: T;
        file?: T;
        id?: T;
      };
  late?: T;
  submittedAt?: T;
  score?: T;
  maxScore?: T;
  feedback?: T;
  rubricScores?:
    | T
    | {
        criterion?: T;
        marks?: T;
        comment?: T;
        id?: T;
      };
  gradedBy?: T;
  gradedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolios_select".
 */
export interface PortfoliosSelect<T extends boolean = true> {
  member?: T;
  title?: T;
  slug?: T;
  summary?: T;
  challenge?: T;
  approach?: T;
  outcome?: T;
  skills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  projectUrl?: T;
  cover?: T;
  coverUrl?: T;
  status?: T;
  visibility?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certificates_select".
 */
export interface CertificatesSelect<T extends boolean = true> {
  member?: T;
  title?: T;
  programName?: T;
  programKey?: T;
  course?: T;
  enrollment?: T;
  issuedBy?: T;
  activeIssuanceKey?: T;
  credentialCode?: T;
  summary?: T;
  skills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  pdf?: T;
  issuedAt?: T;
  expiresAt?: T;
  reissuedFrom?: T;
  revokedAt?: T;
  revokedBy?: T;
  revocationReason?: T;
  notificationStatus?: T;
  status?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-events_select".
 */
export interface AuditEventsSelect<T extends boolean = true> {
  actor?: T;
  action?: T;
  entityType?: T;
  entityId?: T;
  reason?: T;
  before?: T;
  after?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-notes_select".
 */
export interface MemberNotesSelect<T extends boolean = true> {
  member?: T;
  author?: T;
  category?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-registrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  member?: T;
  status?: T;
  ticketCode?: T;
  paystackReference?: T;
  amountPaid?: T;
  currency?: T;
  registeredAt?: T;
  checkedInAt?: T;
  checkedInBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  kind?: T;
  member?: T;
  amount?: T;
  currency?: T;
  status?: T;
  paystackReference?: T;
  paystackAccessCode?: T;
  event?: T;
  course?: T;
  catalogueCourse?: T;
  application?: T;
  enrollment?: T;
  eventRegistration?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-usage-records_select".
 */
export interface AiUsageRecordsSelect<T extends boolean = true> {
  actorType?: T;
  actorKey?: T;
  feature?: T;
  operation?: T;
  provider?: T;
  model?: T;
  status?: T;
  inputChars?: T;
  outputChars?: T;
  inputTokens?: T;
  outputTokens?: T;
  latencyMs?: T;
  sourceCount?: T;
  promptHash?: T;
  errorCode?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-feedback_select".
 */
export interface AiFeedbackSelect<T extends boolean = true> {
  member?: T;
  feature?: T;
  contextKey?: T;
  rating?: T;
  reason?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-knowledge-sources_select".
 */
export interface AiKnowledgeSourcesSelect<T extends boolean = true> {
  course?: T;
  lesson?: T;
  kind?: T;
  title?: T;
  content?: T;
  citationLabel?: T;
  approved?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-drafts_select".
 */
export interface AiDraftsSelect<T extends boolean = true> {
  course?: T;
  lesson?: T;
  kind?: T;
  title?: T;
  content?: T;
  status?: T;
  version?: T;
  parentDraft?: T;
  createdBy?: T;
  provenance?: T;
  controls?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-career-states_select".
 */
export interface AiCareerStatesSelect<T extends boolean = true> {
  member?: T;
  goalSummary?: T;
  confirmedPlan?: T;
  savedOpportunityIds?: T;
  savedCourseIds?: T;
  conversationSummary?: T;
  retentionConsentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  content?: T;
  cover?: T;
  publishedAt?: T;
  readTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  outcomes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  duration?: T;
  lessons?: T;
  price?: T;
  amount?: T;
  currency?: T;
  programKey?: T;
  delivery?: T;
  classroomUrl?: T;
  lmsCourse?: T;
  selarUrl?: T;
  badge?: T;
  image?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  type?: T;
  format?: T;
  pricing?: T;
  amount?: T;
  currency?: T;
  capacity?: T;
  venue?: T;
  address?: T;
  onlineUrl?: T;
  startsAt?: T;
  endsAt?: T;
  date?: T;
  time?: T;
  host?: T;
  summary?: T;
  body?: T;
  registrationUrl?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stories_select".
 */
export interface StoriesSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  programme?: T;
  quote?: T;
  image?: T;
  portfolioUrl?: T;
  permissionConfirmed?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  description?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Public brand, homepage, and social settings. Cohort copy and fees live on Learning programmes marked Cohort.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  /**
   * Default meta description
   */
  description?: string | null;
  opsEmail?: string | null;
  /**
   * Full WhatsApp invite URL
   */
  whatsappInvite?: string | null;
  /**
   * Optional sitewide banner. Leave blank to hide.
   */
  announcementBanner?: string | null;
  /**
   * Short footer explanation of the platform
   */
  footerBlurb?: string | null;
  homepage?: {
    headline?: string | null;
    supportingCopy?: string | null;
    primaryCtaLabel?: string | null;
    secondaryCtaLabel?: string | null;
    secondaryCtaHref?: string | null;
  };
  social?: {
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
  };
  /**
   * Only publish verifiable figures. Leave empty until the client supplies real metrics.
   */
  impactStats?:
    | {
        label: string;
        value: string;
        /**
         * Must be checked to appear on the public site
         */
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  opsEmail?: T;
  whatsappInvite?: T;
  announcementBanner?: T;
  footerBlurb?: T;
  homepage?:
    | T
    | {
        headline?: T;
        supportingCopy?: T;
        primaryCtaLabel?: T;
        secondaryCtaLabel?: T;
        secondaryCtaHref?: T;
      };
  social?:
    | T
    | {
        instagram?: T;
        linkedin?: T;
        twitter?: T;
      };
  impactStats?:
    | T
    | {
        label?: T;
        value?: T;
        verified?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}